config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: { sessions: "users/sessions" }

  root 'tests#index'

  resources :gists, only: %i[index create]

  resources :badges, only: :index

  resources :feedback, only: %i[index create]

  resources :tests, only: :index  do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :gists, only: %i[index destroy]
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/admin.rb
class Admin < User

  validates :fisrt_name, presence: true
  validates :last_name, presence: true

end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :title, presence: true

  validate :validate_count, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_count
    errors.add(:question) if question.answers.count >= 4
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :rule, class_name: "BadgeRule"

  validates :name, :image_url, presence: true
end

app/models/badge_rule.rb
class BadgeRule < ApplicationRecord
  has_many :badges, dependent: :destroy, foreign_key: "rule_id"

end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :gist_url, presence: true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :title, presence: true
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  has_many :questions, dependent: :destroy

  validates :title, presence: true,
                    uniqueness: { scope: :level, message: 'Может быть только один тест с таким названием и уровнем' }

  validates :level, numericality: { greater_than_or_equal_to: 0 }

  scope :easy_level, -> { where(level: 0) }
  scope :elementary_level, -> { where(level: 1) }
  scope :advanced_level, -> { where(level: 2) }
  scope :hard_level, -> { where(level: 3) }
  scope :hero_level, -> { where(level: 4..Float::INFINITY) }

  scope :tests_category, lambda { |category_title|
                           joins(:category).where(categories: { title: category_title }).order(title: :desc)
                         }

  def self.array_tests_category(category_title)
    tests_category(category_title).pluck(:title)
  end

  def http_end_time
    (Time.now + self.passing_time.minutes).httpdate unless self.passing_time.nil?
  end
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  TEST_PASS_RATE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question
  before_validation :set_remaining_time, on: :create

  def completed?
    current_question.nil?
    self.closed?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    self.current_question = next_question
    mark_as_successfully_passed if self.passed?
    save!
  end


  def check_lefted_time
    self.closed = Time.now >= remaining_time
  end


  def result
    (correct_questions.to_f / test.questions.count * 100).to_i
  end

  def passed?
    result >= TEST_PASS_RATE
  end

  def current_question_number
    test.questions.order(:id).where('id <= ?', current_question).count
  end

  def questions_number
    test.questions.count
  end

  def mark_as_successfully_passed
    self.successfully_passed = true
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    self.test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_update_set_next_question
    self.current_question = test.questions.order(:id).where("id > ?", current_question.id).first
  end

  def set_remaining_time
    self.remaining_time = test.http_end_time
  end
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :gists, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages, dependent: :destroy
  has_many :authored_tests, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  def used_tests(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController

  def create
    test_passage = TestPassage.find( params.require(:test_passage_id))
    result = GistQuestionService.new(test_passage.current_question).call

    if result.success?
      current_user.gists.create!(
        question_id: test_passage.current_question.id,
        gist_url: result.url)

        flash[:notice] = view_context.link_to(t('.success', url: result.url), target: '_blank')
      end
    redirect_to test_passage
  end
end

app/controllers/tests_controller.rb
# frozen_string_literal: true

class TestsController < ApplicationController
  before_action :authenticate_user!

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    @tests = Test.all
  end

  def start
    @test = Test.find(params[:id])
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test) # Будет возвращать последнюю строчку из results
  end

  private

  def test_params
    params
      .require(:test)
      .permit(:title, :level, :category_id)
  end

  def set_test
    @test = Test.find(params[:id])
  end

  def rescue_with_test_not_found
    render plain: 'Тест не найден'
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(key)
    case key
    when 'notice' then 'is-success'
    when 'alert' then 'is-danger'
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/footer_helper.rb
# frozen_string_literal: true

module FooterHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to t("helpers.application_helper.repo"), "https://github.com/#{author}/#{repo}", target: :_blank
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    action = question.new_record? ? 'Create' : 'Edit'

    "<h1>#{action} #{question.test.title} Question</h1>".html_safe
  end
end

app/helpers/tests_helper.rb
# frozen_string_literal: true

module TestsHelper
  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_header(test)
    action = test.new_record? ? 'Create' : 'Edit'

    "<h1>#{action} #{test.title} Test</h1>".html_safe
  end

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light bg-primary">
  <%= link_to t('.admin'), admin_tests_path, class: "navbar-brand" %>
  <span class="navbar-text">
    <% if user_signed_in? %>
      <b><%= t('.welcome', name: current_user.first_name  )%>, <%= link_to t('.guru'), admin_tests_path %></b> |
      <button type="button" class="btn btn-outline-dark btn-sm">
        <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
      </button>
    <% else %>
      <%= link_to t('.login'), new_session_path(resource_name) %> |
      <%= link_to t('.signup'), new_registration_path(resource_name) %> |
    <% end %>
    <button type="button" class="btn btn-outline-secondary  btn-sm">
      <%= link_to t('.user'), tests_path %>
    </button>
  </span>
</nav>
<br>

app/views/admin/feedback.html.erb
<div class="row justify-content-center">
  <div class="col col-md-6">
    <center>
      <h1> <%= t('.contact') %> </h1>
    </center>
    <div class="card border-primary">
      <div class="card-body">
        <%= form_with local: true do |form| %>
          <div class="form-group">
            <p>
              <%= form.text_area :message, class: "form-control", placeholder: t('.message'), size: "70x5", required: true %>
            </p>
            <%= form.submit t('.send'), class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
    <br>
    <% if current_user.is_a?(Admin) %>
      <%= link_to t('.back'), admin_tests_path, class: 'btn btn-primary' %>
    <% else %>
      <%= link_to t('.back'), tests_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
      <%= render 'admin/nav' %>
      <%= render 'shared/flash' %>


    <div class="position-absolute bottom-0 start-50 translate-middle-x">
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flash' %>


    <div class="position-absolute bottom-0 start-50 translate-middle-x">
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_errors.hml.erb
<% if resource.errors.present? %>
  <div>
    <h2><%= pluralize(resource.errors.count, 'error') %> detected:</h2>

    <ul><% resource.errors.full_messages.each do |message| %> 
      <li><% message %></li>
    </ul>  
  </div>
<% end %>    

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: "alert alert-danger resource-errors", role: "alert", data: { resource_id: resource.id} do %>
    <h2>
      <%= t('.header', count: resource.errors.count)%>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<div class="container">
    <% flash.each do |key, message| %>
        <div class="notification" <%= flash_class(key) %>>
            <%= message%>
        </div>
    <% end %>
    <%= yield %>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-light text-center text-lg-start">
  <div class="container p-4">
    <div class="row">
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="font-italic"> <%= t('.author_header') %> </h5>
        <p>
          <%= t('.author') %>
        </p>
      </div>
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="font-italic"> <%= t('.links') %> </h5>
         <p>
          <%= github_url('GoncharukAD','TestGuru') %>
        </p>
        <p>
          <a href="https://thinknetica.com" target=_blank> <%= t('.project') %> </a>
        </p>
        <p>
          <%= link_to t('.contact'), feedback_index_path %>
        </p>
       </div>
    </div>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © <%= current_year %> Copyright: TestGuru
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: "navbar-brand" %>
  <span class="navbar-text">
   <% if user_signed_in? %>
      <%= t('.welcome')%>, <b><%= current_user.first_name %></b> <%= link_to t('.guru'), root_path %>
      <button type="button" class="btn btn-outline-dark btn-sm">
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
      </button>
    <% else %>
      <%= link_to t('.login'), new_session_path(resource_name) %> |
      <%= link_to t('.signup'), new_registration_path(resource_name) %>
    <% end %>
    <% if current_user.is_a?(Admin) %>
      <button type="button" class="btn btn-outline-primary btn-sm"><%= link_to t('.admin'), admin_tests_path %></button>
    <% end %>
  </span>
</nav>