config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: { sessions: "users/sessions" }

  root 'tests#index'

  resources :gists, only: %i[index create]

  resources :badges, only: :index

  resources :feedback, only: %i[index create]

  resources :tests, only: :index  do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :gists, only: %i[index destroy]
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :title, presence: true
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  TEST_PASS_RATE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question
  before_validation :set_remaining_time, on: :create

  def completed?
    current_question.nil?
    self.closed?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    self.current_question = next_question
    mark_as_successfully_passed if self.passed?
    save!
  end


  def check_lefted_time
    self.closed = Time.now >= remaining_time
  end


  def result
    (correct_questions.to_f / test.questions.count * 100).to_i
  end

  def passed?
    result >= TEST_PASS_RATE
  end

  def current_question_number
    test.questions.order(:id).where('id <= ?', current_question).count
  end

  def questions_number
    test.questions.count
  end

  def mark_as_successfully_passed
    self.successfully_passed = true
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    self.test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_update_set_next_question
    self.current_question = test.questions.order(:id).where("id > ?", current_question.id).first
  end

  def set_remaining_time
    self.remaining_time = test.http_end_time
  end
end

app/controllers/test_passage_controller.rb
class TestPassagesController < ApplicationController

  before_action: :set_result, only: %i[show update result]

  def show
  end
  
  def result
  end
  
  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed?
      redirect_to_result_result_path(@test_passage)
    else
      render :show
    end  
  end    

  private

  def set_result
    @test_passage = TestPassage.find(params[:id])
  end  
end  

app/controllers/test_passages_controller.rb
# frozen_string_literal: true

class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result]

  def show; end

  def result; end

  def update
    @test_passage.check_lefted_time if @test_passage.test.passing_time.present?
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.closed
      TestsMailer.completed_test(@test_passage).deliver_now
      received_badges = BadgeDepartmentService.new(current_user, @test_passage).call
      flash[:notice] = t(".success") if received_badges.present?
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<% if @test_passage.passed? %>
  <p style="color: green"><%= @test_passage.result %></p>
  <p><%= t('.success') %></p>
<% else %>
  <p style="color: red"><%= @test_passage.result %></p>
  <p><%= t('.failed') %></p>
<% end %>
<%= button_to t('.back'), root_path, method: :get  %>

app/views/test_passages/show.html.erb
<center>
  <h1 class="display-4"><%= t('.header', title: @test_passage.test.title) %></h1>
  <center>
  <h1> <%= t('.passing', test: @test_passage.test.title) %> </h1>
  <br>
  <div id="progress_bar">
    <div class="progress">
      <div class="progress-bar bg-info" role="progressbar"></div>
    </div>
    <%= content_tag :p, "0 %", class: "progress-bar-value", data: { current_question_num: @test_passage.current_question_number, questions_num: @test_passage.test.questions.size} %>
  </div>
  <br>
  <% if @test_passage.test.passing_time.present? %>
    <div id="timer_bar">
      <%= content_tag :p, "", class: "timer-bar-value hide", data: { end_time: @test_passage.remaining_time, test_passage_id: @test_passage.id} %>
    </div>
  <% end %>
</center>
<br>
  <p class="text-start fw-bold fs-5">
    <%= @test_passage.current_question.title %>
  </p>

  <p>
    <%= @test_passage.current_question_number %>/<%= @test_passage.questions_number  %>
  </p>

  <%= form_with url: test_passage_path(@test_passage), local: true, method: :put, html: { id: "choose_answers_form"} do |form|%>
    <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :title, include_hidden: false do |b| %>
      <p>
        <%= b.check_box id: "answer_ids_#{b.object_id}" %>
        <%= b.label %>
      </p>
    <% end %>

    <p><%= link_to t('.qist_question'),  gists_path(:test_passage_id=> @test_passage.id), method: :post %></p>
    <p><%= form.submit t('.next') %></p>
    <p><%= button_to t('.back'), tests_path %></p>
  <% end %>