config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: { sessions: "users/sessions" }

  root 'tests#index'

  resources :gists, only: %i[index create]

  resources :badges, only: :index

  resources :feedback, only: %i[index create]

  resources :tests, only: :index  do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :gists, only: %i[index destroy]
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :title, presence: true

  validate :validate_count, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_count
    errors.add(:question) if question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
# frozen_string_literal: true


class Admin::AnswersController < Admin::BaseController
  before_action :set_answer, only: %i[destroy show edit update]
  before_action :find_question, only: %i[create new]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_answer_not_found

  def edit; end

  def update
      @answer.update ? (redirect_to @answer, t('.success_update')) : (render :edit)
  end

  def show; end

  def destroy
    @answer.destroy
    redirect_to @answer.question, t('.success_delete')
  end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.save ? (redirect_to @answer, t('.success_create')) : (render :new)
  end

  private

  def answer_params
    params.require(:answer).permit(:title)
  end

  def find_question
    @answer = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def rescue_with_answer_not_found
    render plain: t('.not_found')
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.title %> </td>
  <%= link_to 'Edit', edit_admin_answer_path(answer), title: 'Изменить вопрос' %>
  <%= link_to 'Show', admin_answer_path(answer), title: 'Показать вопрос' %>
  <%= link_to 'Delete',
    admin_test_path(answer),
    method: :delete,
    data: { confirm: 'Are you sure?' },
    title: 'Удалить вопрос' %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model:[:admin, @question, @answer ], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_area :title, id: :answer_title, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %><br>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/admin/answers/edit.html.erb
<h1>Edit Answer</h1>

<p>
  <%= @answer.question.title %>
</p>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1>New Answer</h1>

<p>
  <%= @question.title %>
</p>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1>Question</h2>

<p>
 <%= @answer.question.title%>
</p>

<p>
  <%= Answer %>
  <%= @answer.title%>
</p>

<p>
 <%= @answer.correct%>
</p>


<%= link_to 'Back', admin_question_path(@answer.question) %>