config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: { sessions: "users/sessions" }

  root 'tests#index'

  resources :gists, only: %i[index create]

  resources :badges, only: :index

  resources :feedback, only: %i[index create]

  resources :tests, only: :index  do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :gists, only: %i[index destroy]
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :title, presence: true
end

app/controllers/admin/questions_controller.rb
# frozen_string_literal: true


class Admin::QuestionsController < Admin::BaseController
  before_action :set_question, only: %i[destroy show edit update]
  before_action :find_test, only: %i[create new]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def edit; end

  def update
    @question.update ? (redirect_to @question, notice: t('.success_update')) : (render :edit)
  end

  def show; end

  def destroy
    @question.destroy
    redirect_to @question.test, notice: t('.success_delete')
  end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    @question.save ? (redirect_to @question, notice: t('.success_create')) : (render :new)
  end

  private

  def question_params
    params.require(:question).permit(:title)
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def rescue_with_question_not_found
    render plain: t('.not_found')
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    action = question.new_record? ? 'Create' : 'Edit'

    "<h1>#{action} #{question.test.title} Question</h1>".html_safe
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :question_title %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/questions/_question.html.erb
<li>
  <%= question.title %> </td>
  <%= link_to t('.gist_list'), admin_question_gists_path(question) %>
  <%= link_to t('.edit'), edit_admin_question_path(question) %>
  <%= link_to t('.show'), admin_question_path(question) %>
  <%= link_to t('.delete'),
    admin_test_path(question),
    method: :delete,
    data: { confirm:  t('.confirm') }%>
</li>

app/views/admin/questions/edit.html.erb
<%= question_header(@question) %>
<%= render 'form' %>
<%= link_to 'Back', admin_test_path(@question.test_id) %>

app/views/admin/questions/new.html.erb
<h1><%= question_header(@question) %></h1>

<%= render 'form' %>


<%= link_to 'Back', test_questions_path(@test) %>

app/views/admin/questions/show.html.erb
<h1><%= @question.test.title %> Question </h1>
<p>
  <strong>Title:</strong>
   <%= @question.title %><br>
</p>

<h2>Answers</h2>

<%=link_to 'New answer', new_admin_question_answer_path(@question) %>

<ol>
 <%= render @question.answers %>
</ol>

<%= link_to 'Edit', edit_admin_question_path(@question) %>
<%= link_to 'Back', admin_tests_path(@question.test) %>